# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeChatStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WechatOpenSDK', '~> 1.8.1'
  pod 'AFNetworking', '~> 3.2.0'
  # Pods for WeChatStudy

end
